INSERT INTO products(name, price, stock) VALUES ('Paq. de Arroz Costeño',25,30);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Azúcar Blanca Bells',24.5,20);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Aceite de cocina Sao',7,15);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Salchicha San Fernando',8.5,13);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Frijol Canario Bells',7,15);
INSERT INTO products(name, price, stock) VALUES ('Caja de Leche Gloria',21.9,30);
INSERT INTO products(name, price, stock) VALUES ('Fras. de Mermelada Gloria',6.6,16);
INSERT INTO products(name, price, stock) VALUES ('Fras. de Café Nescafé',24.7,19);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Sopa instantánea Marucham',4,17);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Galletas Oreo',16,18);
INSERT INTO products(name, price, stock) VALUES ('Lata de Papas Pringles',8,13);
INSERT INTO products(name, price, stock) VALUES ('Bolsa de Pan Bimbo',10.5,16);
INSERT INTO products(name, price, stock) VALUES ('Pote de Mantequilla Laive',13,20);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Yogurt Gloria',9.9,20);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Queso Philadelphia',10,21);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Jugo de frutas Del Valle',7,22);
INSERT INTO products(name, price, stock) VALUES ('Agua emb. Cielo',3.7,25);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Detergente en polvo Ariel',10,27);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Pap. Higiénico Suave',25.5,29);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Salsa picante Tabasco',16,27);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Arroz Faraon',23.9,24);
INSERT INTO products(name, price, stock) VALUES ('Sazonador Maggi',3,18);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Fideos Bells',5,20);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Galletas Morochas',14,14);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Chocolate Sublime',2,13);
INSERT INTO products(name, price, stock) VALUES ('Caja de Cereal Cochapic',22,25);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Salsa de Soya Kikko',4.2,24);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Leche Laive',27.5,25);
INSERT INTO products(name, price, stock) VALUES ('Doypack Mostaza B&D',9,20);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Sal Marina Emsal',4,26);
INSERT INTO products(name, price, stock) VALUES ('Sazonador Ají-No-Mo-To',3,25);
INSERT INTO products(name, price, stock) VALUES ('Pote de Mermelada Gloria',5.9,28);
INSERT INTO products(name, price, stock) VALUES ('Doypack Salsa de tomate Pomarola',4,24);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Vinagre Blanco Venturo',6.9,24);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Gaseosa Inka Kola',3,25);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Galletas Chokosoda Field',8.5,29);
INSERT INTO products(name, price, stock) VALUES ('Caja de Manzanilla Mc Collins',4,23);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Cerveza Cristal',35,22);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Galletas Oreo',10,20);
INSERT INTO products(name, price, stock) VALUES ('Lata de Café Kirma',18.9,17);
INSERT INTO products(name, price, stock) VALUES ('Caja de Anís Mc Collins',4.9,16);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Gaseosa Pepsi',3,18);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Gaseosa Coca Cola',3.5,15);
INSERT INTO products(name, price, stock) VALUES ('Agua emb. San Mateo',3,19);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Detergente líquido Downy',11.7,22);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Chocolate Vizzio',4,20);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Fideos Cabello de Angel Molitalia',6.5,24);
INSERT INTO products(name, price, stock) VALUES ('Doypack Mayonesa Alacena',7,28);
INSERT INTO products(name, price, stock) VALUES ('Doypack Ketchup Alacena',6,29);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Cerveza Corona',30.5,27);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Chorizo Suiza',14,19);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Jamón Suiza',12,25);
INSERT INTO products(name, price, stock) VALUES ('Bolsa de Pan Unión',11.2,26);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Pallar Costeño',8,28);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Arveja partida Costeño',6.7,26);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Lentejas Costeño',8.9,22);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Quinua Bells',7,22);
INSERT INTO products(name, price, stock) VALUES ('Caja de Cereal Zucosos',22.5,21);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Avena Quaker',11.9,23);
INSERT INTO products(name, price, stock) VALUES ('Lata de Cebada Instantánea Ecco',10.9,24);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Arándanos El Frutero',21.9,28);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Espinaca Bells',5.5,29);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Rábanos Bells',4.9,28);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Tomate Bells',6.5,29);
INSERT INTO products(name, price, stock) VALUES ('Caja de Frugos de Durazno Del Valle',8.9,27);
INSERT INTO products(name, price, stock) VALUES ('Caja de Frugos de Maracuyá Gloria',7.9,23);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Refresco Tampico',7,23);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Refresco Cifrus',8,27);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Aceite Primor',9.5,26);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Azúcar Rubia Bells',20.5,27);
INSERT INTO products(name, price, stock) VALUES ('Pote de Stevia en polvo Bells',18.2,29);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Galleta Morochas',6.5,28);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Wafer Cua Cua',4.2,26);
INSERT INTO products(name, price, stock) VALUES ('Bot. de Aceite Cocinero',8,25);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Wafer Nik',3.5,24);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Galleta Chips Ahoy!',7.1,23);
INSERT INTO products(name, price, stock) VALUES ('Paq. de Galleta Tentación',6.1,20);