INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Arroz Costeño','paqarrozbells.jpeg',25,30);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Azúcar Blanca Bells','paqazucarbells.jpeg',24.5,20);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Aceite de cocina Sao','botdeaceitesao.jpeg',7,15);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Salchicha San Fernando','paqdesalchicha.jpeg',8.5,13);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Frijol Canario Bells','paqdefrijolcanariobells.jpeg',7,15);
INSERT INTO products(name, image, price, stock) VALUES ('Caja de Leche Gloria','cajadelechegloria.jpeg',21.9,30);
INSERT INTO products(name, image, price, stock) VALUES ('Fras. de Mermelada Gloria','frascodemermelada.jpeg',6.6,16);
INSERT INTO products(name, image, price, stock) VALUES ('Fras. de Café Nescafé','frascocafe.jpeg',24.7,19);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Sopa instantánea Marucham','paqdemaruchan.jpeg',4,17);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Galletas Oreo','paqdegalletasoreo.jpeg',16,18);
INSERT INTO products(name, image, price, stock) VALUES ('Lata de Papas Pringles','papaspringles.jpeg',8,13);
INSERT INTO products(name, image, price, stock) VALUES ('Bolsa de Pan Bimbo','bolsadepanbimbo.jpeg',10.5,16);
INSERT INTO products(name, image, price, stock) VALUES ('Pote de Mantequilla Laive','potemantequillalaive.jpeg',13,20);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Yogurt Gloria','botyogurtgloria.jpeg',9.9,20);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Queso Philadelphia','mantequillapiladelhia.jpeg',10,21);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Jugo de frutas Del Valle','botdelvalle.jpeg',7,22);
INSERT INTO products(name, image, price, stock) VALUES ('Agua emb. Cielo','botaguacielo.jpeg',3.7,25);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Detergente en polvo Ariel','detergenteariel.jpeg',10,27);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Pap. Higiénico Suave','paqdepapelsuave.jpeg',25.5,29);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Salsa picante Tabasco','salsapicantetabasco.jpeg',16,27);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Arroz Faraon','paqarrozfaraon.jpeg',23.9,24);
INSERT INTO products(name, image, price, stock) VALUES ('Sazonador Maggi','sazmaggi.jpeg',3,18);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Fideos Bells','paqdefideosbells.jpeg',5,20);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Galletas Morochas','paqgalletasmorochas.jpeg',14,14);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Chocolate Sublime','paqsublime.jpeg',2,13);
INSERT INTO products(name, image, price, stock) VALUES ('Caja de Cereal Cochapic','cajcerealchocapic.jpeg',22,25);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Salsa de Soya Kikko','botsoyakikko.jpeg',4.2,24);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Leche Laive','lechelaive.jpeg',27.5,25);
INSERT INTO products(name, image, price, stock) VALUES ('Doypack Mostaza B&D','mostazaB&D.jpeg',9,20);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Sal Marina Emsal','paqsalmarina.jpeg',4,26);
INSERT INTO products(name, image, price, stock) VALUES ('Sazonador Ají-No-Mo-To','sazajinomoto.jpeg',3,25);
INSERT INTO products(name, image, price, stock) VALUES ('Pote de Mermelada Gloria','mermeladagloria.jpeg',5.9,28);
INSERT INTO products(name, image, price, stock) VALUES ('Doypack Salsa de tomate Pomarola','pomarola.jpeg',4,24);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Vinagre Blanco Venturo','vinagreventuro.jpeg',6.9,24);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Gaseosa Inca Kola','incakola.jpeg',3,25);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Arveja partida Costeño','alberjacosteño.jpeg',6.7,26);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Lentejas Costeño','paqlentejascosteño.jpeg',8.9,22);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Quinua Bells','quinuabells.jpeg',7,22);
INSERT INTO products(name, image, price, stock) VALUES ('Caja de Cereal Zucosos','cerealzucosos.jpeg',22.5,21);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Avena Quaker','avenaquaker.jpeg',11.9,23);
INSERT INTO products(name, image, price, stock) VALUES ('Lata de Cebada Instantánea Ecco','cebadaecco.jpeg',10.9,24);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Arándanos El Frutero','arandanos.jpeg',21.9,28);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Espinaca Bells','espinacas.jpeg',5.5,29);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Rábanos Bells','rabanos.jpeg',4.9,28);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Tomate Bells','tomates.jpeg',6.5,29);
INSERT INTO products(name, image, price, stock) VALUES ('Caja de Frugos de Durazno Del Valle','cajadefrugosdurazno.jpeg',8.9,27);
INSERT INTO products(name, image, price, stock) VALUES ('Caja de Frugos de Maracuyá Gloria','frugosmaracuya.jpeg',7.9,23);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Refresco Tampico','tampico.jpeg',7,23);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Refresco Cifrut','botcifrus.jpeg',8,27);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Aceite Primor','aceiteprimor.jpeg',9.5,26);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Azúcar Rubia Bells','azucarrubiabells.jpeg',20.5,27);
INSERT INTO products(name, image, price, stock) VALUES ('Pote de Stevia en polvo Bells','stevia.jpeg',18.2,29);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Wafer Cua Cua','wafercuacua.jpeg',4.2,26);
INSERT INTO products(name, image, price, stock) VALUES ('Bot. de Aceite Cocinero','aceitecocinero.jpeg',8,25);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Wafer Nik','wafernik.jpeg',3.5,24);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Galleta Chips Ahoy!','galletaschips.jpeg',7.1,23);
INSERT INTO products(name, image, price, stock) VALUES ('Paq. de Galleta Tentación','galletastentacion.jpeg',6.1,20);